// Pkl.Net - Passaro Francesco Paolo 2026
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;
using PklNet.Core;

namespace PklNet.Tools.CodeGen;

/// <summary>
/// Generates C# record types from a Pkl module by evaluating it through pkl-server
/// and inspecting the resulting schema.
/// </summary>
public sealed class PklCodeGenerator
{
    private readonly EvaluatorOptions _options;

    public PklCodeGenerator(EvaluatorOptions? options = null)
        => _options = options ?? EvaluatorOptions.Preconfigured();

    /// <summary>
    /// Generates a C# source file from the given <paramref name="pklFilePath"/>
    /// and writes it to <paramref name="outputDirectory"/>.
    /// </summary>
    public string Generate(string pklFilePath, string outputDirectory, string? @namespace = null, CancellationToken ct = default)
    {
        var moduleName = Path.GetFileNameWithoutExtension(pklFilePath);
        @namespace ??= "Generated";

        // Evaluate the pkl file to get its output text (schema as JSON or pcf).
        // We use the pkl:schema module approach: evaluate the module with output.text
        // and parse it to infer properties.
        using var manager = PklEvaluatorManager.Create(_options);
        using var eval    = manager.NewEvaluator(_options, ct);
        var source = ModuleSource.FromFile(pklFilePath);

        // Get the raw module properties as a dynamic dictionary
        var result = eval.EvaluateModule<Dictionary<string, object?>>(source, ct);

        var sb = GenerateCSharp(moduleName, @namespace, result ?? []);
        var outputPath = Path.Combine(outputDirectory, moduleName + ".pkl.cs");
        Directory.CreateDirectory(outputDirectory);
        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
        return outputPath;
    }

    private static string GenerateCSharp(string className, string ns, Dictionary<string, object?> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Pkl.Net - Passaro Francesco Paolo 2026");
        sb.AppendLine("// Auto-generated by Pkl.Net.Tools — do not edit manually.");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using PklNet.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {ToPascalCase(className)}");
        sb.AppendLine("{");

        foreach (var (key, value) in properties)
        {
            var csType = InferCSharpType(value);
            var propName = ToPascalCase(key);
            sb.AppendLine($"    public {csType} {propName} {{ get; set; }}");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string InferCSharpType(object? value) => value switch
    {
        null           => "object?",
        bool           => "bool",
        long           => "long",
        int            => "int",
        double         => "double",
        float          => "float",
        string         => "string",
        byte[]         => "byte[]",
        List<object?>  => "List<object?>",
        Dictionary<string, object?> => "Dictionary<string, object?>",
        _              => "object"
    };

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        var parts = s.Split('_', '-', ' ');
        var sb = new StringBuilder();
        foreach (var p in parts)
            if (p.Length > 0)
                sb.Append(char.ToUpperInvariant(p[0])).Append(p[1..]);
        // Ensure first char is uppercase
        if (sb.Length > 0) sb[0] = char.ToUpperInvariant(sb[0]);
        return sb.ToString();
    }
}
